<a href="https://colab.research.google.com/github/Ahnkyuwon504/Pythonic/blob/main/1.%20Python%20Struct/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
type(a)

numpy.ndarray

In [4]:
a.shape

(12,)

In [5]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a[2]

array([ 8,  9, 10, 11])

In [7]:
a[2, 1]

np.int64(9)

In [8]:
a[:, 1]

array([1, 5, 9])

In [9]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
floats = np.random.rand(10_000_000).astype('float')
floats[-3:]

array([0.37029602, 0.11502496, 0.64521456])

In [19]:
floats *= .5
floats[-3:]

array([0.18514801, 0.05751248, 0.32260728])

In [20]:
from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0

0.010306406000040624

In [21]:
np.save('floats-10M', floats)
floats2 = np.load('floats-10M.npy', 'r+')

floats2 *= 6
floats2[-3:]

memmap([0.37029602, 0.11502496, 0.64521456])